baseURL = "https://colwyn.net/"
languageCode = "en-us"
title = "Colwyn.net"
theme = "colwyn"

[markup.goldmark.renderer]
unsafe= true

[markup]
  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 2
